# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 10,10 * * *'

env:
  VERCEL: "1"
  VERCEL_ENV: "development"
  VERCEL_URL: ""
  VERCEL_GIT_PROVIDER: ""
  VERCEL_GIT_REPO_SLUG: ""
  VERCEL_GIT_REPO_OWNER: ""
  VERCEL_GIT_REPO_ID: ""
  VERCEL_GIT_COMMIT_REF: ""
  VERCEL_GIT_COMMIT_SHA: ""
  VERCEL_GIT_COMMIT_MESSAGE: ""
  VERCEL_GIT_COMMIT_AUTHOR_LOGIN: ""
  VERCEL_GIT_COMMIT_AUTHOR_NAME: ""
  BIGCOMMERCE_STORE_API_CLIENT_ID: "7czaa4nudep5gc6re0elrsxjcd1elr1"
  BIGCOMMERCE_STORE_API_TOKEN: "ixezf8cskw27pq829hpw0y11eu7479b"
  BIGCOMMERCE_STORE_API_URL: "https://api.bigcommerce.com/stores/yqjrm4u0ka"
  BIGCOMMERCE_STOREFRONT_API_TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJlYXQiOjIxNDcyOTkyMDAsInN1Yl90eXBlIjoyLCJ0b2tlbl90eXBlIjoxLCJjb3JzIjpbXSwiY2lkIjo1NTIxNjYsImlhdCI6MTYxMTY3MDMzOCwic3ViIjoiN2N6YWE0bnVkZXA1Z2M2cmUwZWxyc3hqY2QxZWxyMSIsInNpZCI6MTAwMTYyNzYwMSwiaXNzIjoiQkMifQ.YF-RJSkRm2ePRppN8vjZMGP87Csl3AtuP5atd82O1vNwD7hBcfawfu9HHmKX0-6sBYvmHI91D3YU0iXpDVzR7Q"
  BIGCOMMERCE_STOREFRONT_API_URL: "https://store-yqjrm4u0ka-552166.mybigcommerce.com/graphql"
  BIGCOMMERCE_CHANNEL_ID: "552166"


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Get current time
      uses: josStorer/get-current-time@v2
      id: current-time
      with:
        format: YYYYMMDD-HH
        utcOffset: "-06:00"
    - name: Use current time
      env:
        TIME: "${{ steps.current-time.outputs.time }}"
        R_TIME: "${{ steps.current-time.outputs.readableTime }}"
        F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
        YEAR: "${{ steps.current-time.outputs.year }}"
        DAY: "${{ steps.current-time.outputs.day }}"
      run: echo $TIME $R_TIME $F_TIME $YEAR $DAY
    - name: Automatically create a commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated-Nightly-Push-${{ steps.current-time.outputs.formattedTime }}
        commit_options: '--allow-empty'
        push_options: '--force'
        skip_dirty_check: true    
